AGENTS = [
    {
        "id": "01-web-research-agent",
        "name": "Web Research Agent",
        "framework": "LangGraph",
        "description": "Search the web with Tavily and synthesize a structured research report.",
        "keys": ["OPENAI_API_KEY", "TAVILY_API_KEY"],
        "fields": [
            {"name": "query", "label": "Research query", "type": "textarea", "required": True, "default": "latest advances in AI agents 2024", "flag": "--query"},
        ],
    },
    {
        "id": "02-code-review-agent",
        "name": "Code Review Agent",
        "framework": "LangChain",
        "description": "Review code for correctness, security, performance, style, and improvements.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "file", "label": "Code file", "type": "file", "flag": "--file", "accept": ".py,.js,.ts,.jsx,.tsx,.java,.go,.rs,.cpp,.c,.cs,.rb,.php,.txt"},
            {"name": "code", "label": "Or paste code", "type": "textarea", "flag": "--code"},
            {"name": "language", "label": "Language", "type": "text", "default": "python", "flag": "--language"},
        ],
        "one_of": ["file", "code"],
    },
    {
        "id": "03-pdf-qa-agent",
        "name": "PDF Q&A Agent",
        "framework": "LlamaIndex",
        "description": "Index a PDF and answer questions about its contents.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "pdf", "label": "PDF", "type": "file", "required": True, "flag": "--pdf", "accept": ".pdf"},
            {"name": "question", "label": "Question", "type": "textarea", "required": True, "flag": "--question"},
        ],
    },
    {
        "id": "04-sql-query-agent",
        "name": "SQL Query Agent",
        "framework": "LangChain",
        "description": "Ask natural-language questions against a SQLite database.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "db", "label": "SQLite database (optional; blank uses demo DB)", "type": "file", "flag": "--db", "accept": ".sqlite,.sqlite3,.db"},
            {"name": "question", "label": "Question", "type": "textarea", "required": True, "flag": "--question"},
            {"name": "allow_write", "label": "Allow database writes", "type": "checkbox", "flag": "--allow-write", "danger": True},
        ],
    },
    {
        "id": "05-email-drafting-agent",
        "name": "Email Drafting Agent",
        "framework": "CrewAI",
        "description": "Draft an email from context, tone, and recipient information.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "context", "label": "Email context / purpose", "type": "textarea", "required": True, "default": "Follow up on our product demo from last Tuesday. They seemed interested but haven't responded.", "flag": "--context"},
            {"name": "tone", "label": "Tone", "type": "text", "default": "professional and friendly", "flag": "--tone"},
            {"name": "recipient", "label": "Recipient", "type": "text", "default": "a potential client", "flag": "--recipient"},
        ],
    },
    {
        "id": "06-news-summarizer-agent",
        "name": "News Summarizer Agent",
        "framework": "LangChain",
        "description": "Fetch current articles from NewsAPI and summarize them with an LLM.",
        "keys": ["OPENAI_API_KEY", "NEWS_API_KEY"],
        "fields": [
            {"name": "topic", "label": "Topic", "type": "text", "required": True, "default": "artificial intelligence", "flag": "--topic"},
            {"name": "count", "label": "Article count", "type": "number", "default": 5, "min": 1, "max": 20, "flag": "--count"},
        ],
    },
    {
        "id": "07-github-issue-triager",
        "name": "GitHub Issue Triager",
        "framework": "LangGraph",
        "description": "Triage a GitHub issue from a URL or pasted title/body.",
        "keys": ["OPENAI_API_KEY"],
        "optional_keys": ["GITHUB_TOKEN"],
        "fields": [
            {"name": "issue_url", "label": "Issue URL", "type": "text", "flag": "--issue-url"},
            {"name": "title", "label": "Or issue title", "type": "text", "flag": "--title"},
            {"name": "body", "label": "Issue body", "type": "textarea", "flag": "--body"},
        ],
        "one_of": ["issue_url", "title"],
    },
    {
        "id": "08-data-analysis-agent",
        "name": "Data Analysis Agent",
        "framework": "LangChain",
        "description": "Analyze CSV/XLSX data by letting LangChain generate and execute pandas code.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "file", "label": "CSV or Excel file", "type": "file", "flag": "--file", "accept": ".csv,.xlsx,.xls"},
            {"name": "question", "label": "Question", "type": "textarea", "required": True, "flag": "--question"},
            {"name": "allow_dangerous_code", "label": "Allow model-generated Python execution", "type": "checkbox", "flag": "--allow-dangerous-code", "required": True, "danger": True},
        ],
    },
    {
        "id": "09-resume-parser-agent",
        "name": "Resume Parser Agent",
        "framework": "LangChain",
        "description": "Parse a resume and optionally match it against a job description.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "resume", "label": "Resume", "type": "file", "required": True, "flag": "--resume", "accept": ".pdf,.txt"},
            {"name": "job_desc", "label": "Job description (optional)", "type": "textarea", "flag": "--job-desc"},
        ],
    },
    {
        "id": "10-meeting-notes-agent",
        "name": "Meeting Notes Agent",
        "framework": "LangChain",
        "description": "Turn a transcript into structured notes, decisions, and action items.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "transcript", "label": "Transcript file", "type": "file", "flag": "--transcript", "accept": ".txt,.md"},
            {"name": "text", "label": "Or paste transcript", "type": "textarea", "flag": "--text"},
        ],
        "one_of": ["transcript", "text"],
    },
    {
        "id": "11-stock-research-agent",
        "name": "Stock Research Agent",
        "framework": "LangChain",
        "description": "Research a public stock using market data and an LLM synthesis step.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "ticker", "label": "Ticker", "type": "text", "required": True, "placeholder": "AAPL", "flag": "--ticker"},
        ],
    },
    {
        "id": "12-travel-planner-agent",
        "name": "Travel Planner Agent",
        "framework": "CrewAI",
        "description": "Create a trip plan from destination, duration, budget, and interests.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "destination", "label": "Destination", "type": "text", "required": True, "default": "Tokyo, Japan", "flag": "--destination"},
            {"name": "days", "label": "Days", "type": "number", "default": 7, "min": 1, "max": 60, "flag": "--days"},
            {"name": "budget", "label": "Budget (USD)", "type": "number", "default": 3000, "min": 0, "flag": "--budget"},
            {"name": "interests", "label": "Interests", "type": "text", "default": "food, culture, technology", "flag": "--interests"},
        ],
    },
    {
        "id": "13-customer-support-agent",
        "name": "Customer Support Agent",
        "framework": "LangGraph",
        "description": "RAG support agent with escalation logic. Uses the built-in CloudSync sample KB or uploaded .txt/.md files.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "kb_files", "label": "Knowledge-base files (optional)", "type": "multifile", "accept": ".txt,.md"},
            {"name": "message", "label": "Customer message", "type": "textarea", "required": True},
        ],
        "stdin_field": "message",
    },
    {
        "id": "14-social-media-agent",
        "name": "Social Media Content Agent",
        "framework": "CrewAI",
        "description": "Generate social content across selected platforms.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "topic", "label": "Topic", "type": "textarea", "required": True, "default": "How AI is transforming software development in 2025", "flag": "--topic"},
            {"name": "brand", "label": "Brand (optional)", "type": "text", "flag": "--brand"},
            {"name": "platforms", "label": "Platforms", "type": "text", "default": "twitter,linkedin,instagram", "flag": "--platforms"},
        ],
    },
    {
        "id": "15-unit-test-generator",
        "name": "Unit Test Generator",
        "framework": "LangChain",
        "description": "Generate a pytest test suite from Python code.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "file", "label": "Python file", "type": "file", "flag": "--file", "accept": ".py"},
            {"name": "code", "label": "Or paste Python code", "type": "textarea", "flag": "--code"},
        ],
        "one_of": ["file", "code"],
    },
    {
        "id": "16-documentation-writer",
        "name": "Documentation Writer Agent",
        "framework": "LangChain",
        "description": "Generate README documentation and/or add docstrings to Python code.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "file", "label": "Python file", "type": "file", "flag": "--file", "accept": ".py"},
            {"name": "code", "label": "Or paste Python code", "type": "textarea", "flag": "--code"},
            {"name": "format", "label": "Output", "type": "select", "default": "both", "options": ["readme", "docstrings", "both"], "flag": "--format"},
        ],
        "one_of": ["file", "code"],
    },
    {
        "id": "17-recipe-agent",
        "name": "Recipe Recommendation Agent",
        "framework": "LangChain",
        "description": "Create recipes from ingredients, diet preferences, time, and serving count.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "ingredients", "label": "Ingredients", "type": "textarea", "required": True, "default": "chicken breast, garlic, lemon, rosemary", "flag": "--ingredients"},
            {"name": "diet", "label": "Diet (optional)", "type": "text", "flag": "--diet"},
            {"name": "time", "label": "Max cooking time (minutes, 0 = no limit)", "type": "number", "default": 0, "min": 0, "flag": "--time"},
            {"name": "servings", "label": "Servings", "type": "number", "default": 2, "min": 1, "max": 50, "flag": "--servings"},
        ],
    },
    {
        "id": "18-job-application-agent",
        "name": "Job Application Agent",
        "framework": "CrewAI",
        "description": "Generate application material from a job description and candidate profile.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "job_desc", "label": "Job description", "type": "textarea", "required": True, "flag": "--job-desc"},
            {"name": "candidate", "label": "Candidate profile", "type": "textarea", "required": True, "flag": "--candidate"},
        ],
    },
    {
        "id": "19-competitive-analysis-agent",
        "name": "Competitive Analysis Agent",
        "framework": "LangGraph",
        "description": "Produce a structured competitive analysis for a company and industry.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "company", "label": "Company", "type": "text", "required": True, "default": "Notion", "flag": "--company"},
            {"name": "industry", "label": "Industry", "type": "text", "required": True, "default": "productivity and collaboration software", "flag": "--industry"},
        ],
    },
    {
        "id": "20-multi-agent-debate",
        "name": "Multi-Agent Debate System",
        "framework": "LangChain",
        "description": "Run a multi-agent debate for a topic over one to four rounds.",
        "keys": ["OPENAI_API_KEY"],
        "fields": [
            {"name": "topic", "label": "Debate topic", "type": "textarea", "required": True, "default": "AI will create more jobs than it eliminates over the next decade", "flag": "--topic"},
            {"name": "rounds", "label": "Rounds", "type": "number", "default": 2, "min": 1, "max": 4, "flag": "--rounds"},
        ],
    },
]

AGENT_BY_ID = {agent["id"]: agent for agent in AGENTS}
